index:
    path: /{_locale}
    controller: App\Controller\MainController::index
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
contact:
    path: /contact
    controller: App\Controller\ContactController::contact
