dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    methods: GET